#!/usr/bin/env ruby

require_relative '../common'

module Antichamber
  extend GameSave

  def self.active
    if OS.windows?
      Windows.steamapps + '/common/Antichamber/Binaries/Win32/SavedGame.bin'
    elsif OS.mac?
      Mac.appSupport + '/Unreal Tournament 3/SavedGame.bin'
    else
      raise 'Unsupported OS'
    end
  end

  def self.stored
    File.dirname(__FILE__) + '/SavedGame.bin'
  end
end
Antichamber.run
