#!/usr/bin/env ruby

require '../common'

if OS.windows?
  active = Windows.documents + '/My Games/Binding of Isaac Rebirth'
elsif OS.mac?
  active = Mac.appSupport + '/Binding of Isaac Rebirth'
else
  STDERR.puts 'Unsupported OS'
  exit 1
end
stored = File.dirname(__FILE__) + '/data'

if ARGV == ['load']
  FileUtils.cp_r "#{stored}/.", active
elsif ARGV == ['save']
  FileUtils.mkdir_p stored
  FileUtils.cp_r "#{active}/.", stored
  FileUtils.rm "#{stored}/log.txt"
else
  STDERR.puts "Usage: #{$0} (load|save)"
  exit 1
end
