#!/usr/bin/env ruby

require_relative '../common'

module BOIRebirth
  extend GameSave

  def self.active
    if OS.windows?
      Windows.documents + '/My Games/Binding of Isaac Rebirth'
    elsif OS.mac?
      Mac.appSupport + '/Binding of Isaac Rebirth'
    else
      raise 'Unsupported OS'
    end
  end

  def self.stored
    File.dirname(__FILE__) + '/data'
  end

  def self.save
    super
    FileUtils.rm_f "#{self.stored}/log.txt"
  end
end
BOIRebirth.run
