#!/usr/bin/env ruby

require_relative '../common'

module BOIRebirth
  extend GameSave

  def self.active
    # TODO: fix windows support (probably moved with v1.032)
    # is it the same as mac below?
    
    # if OS.windows?
    #   Windows.documents + '/My Games/Binding of Isaac Rebirth'
    if OS.mac?
      Mac.steamUserData + '/250900'
    else
      raise 'Unsupported OS'
    end
  end

  def self.stored
    File.dirname(__FILE__) + '/data'
  end

  def self.save(force = true)
    super
    FileUtils.rm_f "#{self.stored}/log.txt"
  end
end
BOIRebirth.run
